# Generated by Django 5.2.8 on 2025-11-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
